### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by h-jia** [danijoo/tmux-plugin-simple-gpu#1]
Closed

**Comment by dnlbauer** [comment]
Hi. Glad to hear you like it. I updated the plugin so it should now handle multiple gpus natively. It will simply list the usage for all of them:

Example output with 2 GPUs:
![image](https://user-images.githubusercontent.com/4690162/89121229-68c6fc00-d4bd-11ea-97c8-dd8f8081aca9.png)

Let me know if it doesn't work for you!
